# Generated by Django 4.2 on 2023-05-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="receipt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="receipt.receipt"
            ),
        ),
    ]
