# Generated by Django 4.2 on 2023-04-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
    ]
