# Generated by Django 4.2 on 2023-05-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("post", "0003_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.user"
            ),
        ),
    ]
