# Generated by Django 4.2 on 2023-05-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_receipt_id"),
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ingredient_list", name="ingredient_id",),
        migrations.RemoveField(model_name="ingredient_list", name="receipt_id",),
        migrations.RenameField(
            model_name="receipt", old_name="name", new_name="title",
        ),
        migrations.RemoveField(model_name="receipt", name="image",),
        migrations.DeleteModel(name="Ingredient",),
        migrations.DeleteModel(name="Ingredient_list",),
    ]
