# Generated by Django 4.2 on 2023-05-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0002_remove_ingredient_list_ingredient_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt", old_name="title", new_name="r_title",
        ),
    ]
